### ISSUE TITLE
Fix link in "Common issues customers experience when using Auto-scale with Service Fabric clusters.md"

### ISSUE THREAD

**Issue by pisees** [Azure/Service-Fabric-Troubleshooting-Guides#142]
I believe the link in "https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Cluster/Common%20issues%20customers%20experience%20when%20using%20Auto-scale%20with%20Service%20Fabric%20clusters.md#common-issues-customers-experience-when-using-auto-scale-with-service-fabric-clusters" to "Reference: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-scale-up-down"  needs to be updated to https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-scale-in-out

**Comment by sedwardstx** [comment]
this has been updated to reflect the new URL, thanks for pointing this out.
