### ISSUE TITLE
Download for http://aka.ms/event-log-manager.ps1 is not working

### ISSUE THREAD

**Issue by pisees** [Azure/Service-Fabric-Troubleshooting-Guides#154]

**Comment by pisees** [comment]
I do see that https://aka.ms/event-log-manager.ps1 works. This is important because this link is referenced in https://raw.githubusercontent.com/Azure/Service-Fabric-Troubleshooting-Guides/master/Scripts/sf-collect-node-info.ps1

**Comment by jagilber** [comment]
fixed aka.ms
was pointing to technet
now pointing to git repo
http://aka.ms/event-log-manager.ps1

**Comment by sedwardstx** [comment]
fix confirmed, thanks for opening this issue pisees and the quick fix by jagilber!
