### ISSUE TITLE
Is there any settings to log a application crash because of a StackOverflowException?

### ISSUE THREAD

**Issue by MartinDemberger** [Azure/Service-Fabric-Troubleshooting-Guides#163]
Today I had a StackOverflowException in my production system.

AppInsights and FabricExplorer showed all es corret running but the erroneous service was restarting the whole time.

Is there a possibility to log a StackOverflowExceptoin in AppInsights and store a memory dump on the VM so there is a possibility to analyse this error?

My solution was to take a few memory dumps by hand. I had luck and one of them showed me the stack trace.

**Comment by inputoutputcode** [comment]
SFX should show the process exits on the level for the application. The types StackOverflowException or OutOfMemoryException are both not reliable to catch by monitoring tools which live in the same context. I'm not an expert for Application Insights SDK, please consider to open the question here: https://github.com/microsoft/ApplicationInsights-dotnet/issues

The best solution is to fix the code. I think procdump or debugdiag are the best tools to analyze it.
I know there is a preview feature for AI to monitor memory leaks: https://docs.microsoft.com/en-us/azure/azure-monitor/app/proactive-potential-memory-leak
There might be an option to replace the TelemetryChannel to have something on disk, but not tested.

Please take a look at the observer project to monitor memory, event log or manage process restarts.
https://github.com/microsoft/service-fabric-observer

**Comment by sedwardstx** [comment]
You can also configure WER (Windows Error Reporting) to capture dumps for your application.

https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps?redirectedfrom=MSDN
