### ISSUE TITLE
Nodes FabricNode Certificate Expiration.md broken content

### ISSUE THREAD

**Issue by v-karbovnichy** [Azure/Service-Fabric-Troubleshooting-Guides#180]
https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Known_Issues/Nodes%20FabricNode%20Certificate%20Expiration.md has missing content in the end of Mitigation section, and broken links formatting in Resolution section.

**Comment by sedwardstx** [comment]
this is fixed, thanks for reporting.
