### ISSUE TITLE
Dead link on Mirantis-Guidance

### ISSUE THREAD

**Issue by rganz** [Azure/Service-Fabric-Troubleshooting-Guides#209]
In this [chapter](https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Deployment/Mirantis-Guidance.md#scenario-1option-1-full-rebuild-the-cluster) there is a link **"How To: Rebuild Azure Service Fabric cluster (minimal version)"** which leads only to "#". I'd like to take this path for upgrading, but first I need to read this How To...

**Comment by sedwardstx** [comment]
this has been resolved
