### ISSUE TITLE
The wrong URL of the PowerShell script is included in the template example

### ISSUE THREAD

**Issue by JerryZhangMS** [Azure/Service-Fabric-Troubleshooting-Guides#238]
https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Deployment/Mirantis-Installation.md

In the above doc, in the ARM template example, the URL of the PS script is "https://raw.githubusercontent.com/Azure/Service-Fabric-Troubleshooting-Guides/chrpap/dockermigration/Scripts/Mirantis-Install.ps1". But it's easy to find out that this URL will only return 404 error. 
`"settings": {
    "fileUris": [
        "https://raw.githubusercontent.com/Azure/Service-Fabric-Troubleshooting-Guides/chrpap/dockermigration/Scripts/Mirantis-Install.ps1"
    ],
    "commandToExecute": "[concat('powershell -ExecutionPolicy Unrestricted -File .\\', 'Mirantis-Install.ps1')]"
}`

Should we replace it by correct URL https://raw.githubusercontent.com/Azure/Service-Fabric-Troubleshooting-Guides/master/Scripts/Install-Mirantis.ps1 ?

The template example here should be:

`"settings": {
    "fileUris": [
        "https://raw.githubusercontent.com/Azure/Service-Fabric-Troubleshooting-Guides/master/Scripts/Install-Mirantis.ps1"
    ],
    "commandToExecute": "[concat('powershell -ExecutionPolicy Unrestricted -File .\\', 'Install-Mirantis.ps1')]"
}`

**Comment by sedwardstx** [comment]
this was fixed in https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/commit/c60de7b8c05e21d6b2b33a56b2fbc46859ef6346 back in Oct.  Your branch may be out of date?

**Comment by JerryZhangMS** [comment]
@sedwardstx  The fix you shared is about the hyperlink to the script, but what I want to mention is the link in the template :) They are different ones.
![image](https://user-images.githubusercontent.com/108329002/211987157-c3a3e05e-7871-472e-b1d0-61921b413166.png)
