### ISSUE TITLE
Hyper-V not enabled and cause failure when using Windows Server 2022 + custom script extension to run containerized application with hyper-V isolation

### ISSUE THREAD

**Issue by JerryZhangMS** [Azure/Service-Fabric-Troubleshooting-Guides#239]
Hi authors, please kindly have a check of this issue and see if we should add some additional explanations in the document.

I followed https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Deployment/Mirantis-Guidance.md#scenario-2-customer-is-hosting-azure-service-fabric-node-type-using-deprecated-windows-server-images-with-containers-and-does-host-containers-in-docker-as-part-of-their-applications, scenario 2, option 1 to do a test.

I recreated a new SF cluster with Windows Server 2022 and followed https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Deployment/Mirantis-Installation.md to install the Mirantis Container Runtime. Deployment and installation are both successful.

But when I tried to run a containerized application with Windows Server 2016 as its base OS image, according to https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-11 , we can only use hyper-V isolation, not process isolation.

Then after deploying the application with hyper-V isolation, it returned following error in SF explorer:

**'System.Hosting' reported Error for property 'CodePackageActivation:Code:EntryPoint:xxx.
There was an error during CodePackage activation.System.Fabric.FabricException (-2147017731)
Failed to start Container. ContainerName=xxx, ApplicationId=xxx, ApplicationName=xxx. DockerRequest returned StatusCode=InternalServerError with ResponseBody={"message":"hcsshim::CreateComputeSystem xxx: The request is not supported."}**

![image](https://user-images.githubusercontent.com/108329002/207997733-eeaccedd-f25d-4c0f-a5e5-fbb1ff38cd58.png)

By RDP into the nodes, I confirmed that the container runtime was installed successfully and the container image was downloaded successfully also.
![image](https://user-images.githubusercontent.com/108329002/207997836-4a546d67-3314-441a-bd54-9481977a49e3.png)

After double-checking, I found out that the hyper-V was not installed and enabled by default in Windows Server 2022.
![image](https://user-images.githubusercontent.com/108329002/207998089-5faeb5fb-9973-4239-a8f3-ba4ce1c728f4.png)

And this caused the error above.

I tried to enable the hyper-V manually on one specific node and then deleted the existing application and recreated it. And this time, the application could be started successfully. This proved that the disabled hyper-V feature was actually the root cause.

Then later, I found one possible solution for this scenario. **We could add another PS script, for example hyperv.ps1, to enable the hyper-V feature with following commands:**
`Install-WindowsFeature -Name Hyper-V -IncludeAllSubFeature -IncludeManagementTools
Restart-Computer -Force`

Another new PS script, like run.ps1, to run both of hyperv.ps1 and Install-Mirantis.ps1
`.\Install-Mirantis.ps1
.\enablehyperv.ps1`

Then modify the VMSS extension according to https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows#using-multiple-scripts to be able to run multiple custom scripts at same time.

The final version of extension should seem like:
`"settings": {
    "fileUris": [
        "https://github.com/JerryZhangMS/SFcontainer/releases/download/enable-hyperv/enablehyperv.ps1",
        "https://github.com/JerryZhangMS/SFcontainer/releases/download/enable-hyperv/environment.ps1",
        "https://raw.githubusercontent.com/Azure/Service-Fabric-Troubleshooting-Guides/master/Scripts/Install-Mirantis.ps1"
    ],
    "commandToExecute": "[concat('powershell -ExecutionPolicy Unrestricted -File .\\', 'environment.ps1')]"
}
`

After upgrading the VMSS with this new extension, the application could be run without error.
![image](https://user-images.githubusercontent.com/108329002/207999036-4a09368e-1858-4aaa-8938-329d80dc74cc.png)
![image](https://user-images.githubusercontent.com/108329002/207999050-9ec42033-b380-493c-9290-1f99f2f12d59.png)

**Comment by JerryZhangMS** [comment]
@sedwardstx  Of course, that's my pleasure. I'll make the change and submit a pull request later.

**Comment by JerryZhangMS** [comment]
@sedwardstx  I've finished the modification of the page but I **don't have the permission to submit the pull request**. Will you be able to update the change or give my account permission for that? Thanks.

**Comment by sedwardstx** [comment]
Hi Jerry, please fork the repo and make your changes in your local branch, then make the PR back into the main

**Comment by JerryZhangMS** [comment]
Hi @sedwardstx , here it is  https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/pull/248

**Comment by JerryZhangMS** [comment]
Hi @sedwardstx , I checked the PR https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/pull/248 and found "At least 1 approving review is required by reviewers with write access." Could you please help find someone to review and approve this?

**Comment by sedwardstx** [comment]
done, sorry for delays
