### ISSUE TITLE
Some images are not included in the affected image list

### ISSUE THREAD

**Issue by JerryZhangMS** [Azure/Service-Fabric-Troubleshooting-Guides#240]
Hi authors,

I'm following this document https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Deployment/Mirantis-Guidance.md#list-of-affected-azure-os-images and find a small issue.

In Azure, if we use command az vm image list --offer "WindowsServer" --sku "with-container" --all  to list all the available OS image for Windows Server with container pre-installed, there will be three images with "WindowsServerSemiAnnual" as offer. 

"Datacenter-Core-1803-with-Containers-smalldisk",  "Datacenter-Core-1709-with-Containers-smalldisk" and "Datacenter-Core-1809-with-Containers-smalldisk"

Per my understanding, these three images will also be affected by this. Could you please kindly confirm this point?

If it's true that these three will also be affected, should we also add it into the document, affected OS image list?

**Comment by sedwardstx** [comment]
yes, I agree we need to add these images.  Updating in this PR - https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/pull/241

**Comment by sedwardstx** [comment]
updated
