### ISSUE TITLE
Delete SFLog files 

### ISSUE THREAD

**Issue by mibdah123** [Azure/Service-Fabric-Troubleshooting-Guides#264]
Hi ,
Can we delete the SFlog files that located in the service fabric cluster orchestrator node !

**Comment by sedwardstx** [comment]
These are sparse files that are used by some of the Service Fabric System Services, these should not be deleted.  If you look at the file properties in Explorer, you will notice the size and size on disk don't line up (more info: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365564(v=vs.85).aspx).
