### ISSUE TITLE
Performance Counters thresholds useful as troubleshooting guide

### ISSUE THREAD

**Issue by EVMartinez** [Azure/Service-Fabric-Troubleshooting-Guides#38]
Hello Team,

I noticed that, service fabric has a lot of objects inside perfmon for almost (if not all) the service fabric components. For standalone clusters it will be really useful if you provide specific guidance about which counters could be an indication that Service Fabric is having problems or potentially approaching to a performance degradation.

**Comment by jagilber** [comment]
almost all performance issues are found using the general performance counters: cpu, memory, disk, network:
rough guidelines of possible performance issues:
\Memory\Available MBytes < 1000MB depending on sku
\TCPv4\Segments Received/sec 
\TCPv4\Segments Sent/sec
\TCPv4\Segments Retransmitted/sec no large spikes and no spikes associated with cpu
\Paging File(*)\* > 20%
\PhysicalDisk(0 C:)\Avg. Disk Queue Length > 3 sustained
\PhysicalDisk(1 D:)\Avg. Disk Queue Length > 3 sustained
\Processor(_Total)\* > 80% sustained

service fabric specific issues
high cpu or memory in fabric*.exe processes

rarely do we use service fabric specific counters to troubleshoot performance

**Comment by inputoutputcode** [comment]
Closing for now
