### ISSUE TITLE
Accessing a microservice hosted in Service Fabric with a specific char in query string make SF Gateway crash

### ISSUE THREAD

**Issue by crob1** [Azure/Service-Fabric-Troubleshooting-Guides#39]
Hi guys,

I have several microservices hosted in SF. I'm using SF reverse proxy to access my services with their names like with the following type of URL:
http://localhost:19081/appname/servicename/path?query=something

I've noticed if I put some specific chars in the query string like [, ], or | it makes the SF gateway crash and all services cannot be accessed with a connection refused HTTP result. The gateway heal itselft but if the request is performed again many times, the SF cluster itself crashes.

Charles

**Comment by guibirow** [comment]
This should be submitted to this repo:
https://github.com/Azure/service-fabric-issues/issues
