### ISSUE TITLE
Service Fabric certificate upgrade

### ISSUE THREAD

**Issue by Chemlin** [Azure/Service-Fabric-Troubleshooting-Guides#68]
I need to update my Local service fabric installation from using certificate thumbprint to CommonName.

**Comment by sedwardstx** [comment]
you would need to perform a cluster configuration upgrade to switch between certificate thumbprint and common name: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-config-upgrade-windows-server

I do not have a step by step tutorial on this however you should be able to compare the example templates that come with the Standalone SF install package:

compare these to see the differences in how the certificate/security settings are declared.
- ClusterConfig.Windows.X590.DevCluster.json
- ClusterConfig.Windows.X509.MultiMachine.json
