### ISSUE TITLE
Out of disc space because of CM.edb

### ISSUE THREAD

**Issue by MartinDemberger** [Azure/Service-Fabric-Troubleshooting-Guides#69]
On one of our node drive D: is very low on Disc space. I found that file CM.edb (D:\SvcFab\_XXXXXXX_1\Fabric\work\CM\P_00000000-0000-0000-0000-000000002000\R_131858949658938295\CM.edb) has about 28 GB.
I only was able to delete this file by stopping the process fabric.exe

What's the content of this file? Can I limit the used disc space? Is killing fabric.exe the right Thing?

**Comment by sedwardstx** [comment]
Hi Martin,

These work folders are where the internal Replica state for your stateful Services and Actors are stored.  You should not manually try to delete these as it can cause data loss for your service.  

The 28 GB is going to be your service's state (the data) which you are storing in Reliable Collections or Queues.  Depending on the design of your service, the type(schema) of your Dictionary and # of records you keep in each partition of your Reliable collection will affect the on-disk size.  You can spread the disk usage over more nodes by partitioning the service such that only a portion of the records are stored in each replica, see this for more details: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-concepts-partitioning#get-started-with-partitioning
