### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by MikkelHegn** [Azure/Service-Fabric-Troubleshooting-Guides#74]
This article: https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Cluster/Troubleshooting%20failed%20Fabric%20Upgrade.md

Has two references to a dead link: https://msdn.microsoft.com/en-us/library/azure/mt163586.aspx

**Comment by aljo-microsoft** [comment]
removed link
