### ISSUE TITLE
How to configure Azure Service Fabric Cluster for closed networks -- need guide

### ISSUE THREAD

**Issue by jlongo62** [Azure/Service-Fabric-Troubleshooting-Guides#88]
We need a **complete/clear** guide on how to deploy Service Fabric on closed networks....

I have created an ARM to deploy a cluster onto a closed network (based on the default Open Network portal created template.)
Several Issues exist:
1 - SF wants to download.microsoft.com[Internet] -- come on guys, this should be intercepted by Azure and directed to trusted site; alternatively, how to redirect this to my own site/storage blobs or turn it off. _This should be set in the portal, I should not be expected me to set lmhost file in a VM (unless there is a clear extension to do it -not DSC-you only get one DSC)_. I see this issue way too much inside Azure. **In the real world, Firewalls are disabled to the internet, DNS is off limits. Devs have little/no control of the network.**
2 -**SecurityApi_CertGetCertificateChain** Security | CrlCheckingFlag is buried in this site. The Federation|X509CertChainFlags setting is not applicable (at least in the portal)-at least it is there.
3 - How do I configure the NSG ? What Azure service tags are needed ? Ports/Protocols, etc.

I am stuck in a constant state of Upgrade or Warning.

**Comment by inputoutputcode** [comment]
Hi,

Please check the following docs.

List of all mandatory network security rules including the explanation:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-best-practices-networking#network-security-rules

Here we explain how to lockdown a cluster completely, basically a load balancer/public IP both with Standard SKU including some NSGs is enough:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-patterns-networking 

How to get rid of SecurityApi_CertGetCertificateChain or how to disable CLR (not recommended):
https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Security/SecurityApi_CertGetCertificateChain%20-%20CTL%20accessibility%20-%20CRL%20slow%20warnings.md 

Christian
