### ISSUE TITLE
SF unable to authenticate with primary certificate.md

### ISSUE THREAD

**Issue by wugangzhang** [Azure/Service-Fabric-Troubleshooting-Guides#95]
"Or you can revert to the old algorithm by using following command
Set-AzureRmServiceFabricSetting -ResourceGroupName rgname -Name clustername -Section "Security" -Parameter "UseSecondaryIfNewer" -Value "false"

The above statement is kind of misleading based on my observations. After changing UseSecondaryIfNewe to false, ONLY the primary certificate will work. (The secondary will stop working)

**Comment by sedwardstx** [comment]
I updated the statement to make it more clear.  You are correct in your observation, the older algorithm will only use the primary certificate.  The secondary slot was only used to stage new certs in preparation for rollover
